version: '3.4'

services:
  client:
    build: client
    ports: 
      - "4200:80"

  server:
    build: server
    ports: 
      - "5200:5200"
    links:
      - database

  database:
    image: mongo:4.4.6
    ports: 
      - "27017:27017"

